<?php $tokens = array_map('api_token_public', api_tokens_load()); ?>
<div class="page-header"><div><h1 class="page-title">API</h1><p class="page-subtitle">Bearer keys for authenticated JSON automation</p></div></div>
<div class="card" style="margin-bottom:16px"><div class="card-header"><h3>Generate new key</h3></div><div class="card-pad"><div class="flex gap-2"><input class="input" id="apiLabel" maxlength="80" placeholder="Key label, e.g. deployment script"><button class="btn btn-primary" id="apiGenerate"><i data-lucide="key-round"></i>Generate</button></div></div></div>
<div class="card" id="apiReveal" style="display:none;margin-bottom:16px;border-color:rgba(245,158,11,.45)"><div class="card-header"><h3>Copy this token now</h3><span class="badge badge-orange">Shown once</span></div><div class="card-pad"><div class="flex gap-2"><input class="input mono" id="apiPlain" readonly><button class="btn btn-secondary" id="apiCopy"><i data-lucide="copy"></i>Copy</button></div></div></div>
<div class="card" style="margin-bottom:16px"><div class="card-header"><h3>API keys</h3><span class="muted"><?= count($tokens) ?> active</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Label</th><th>Created</th><th>Last used</th><th></th></tr></thead><tbody>
<?php foreach ($tokens as $token): ?><tr><td style="font-weight:600"><?= e($token['label']) ?></td><td class="mono text-tertiary"><?= e($token['created_at']) ?></td><td class="mono text-tertiary"><?= e($token['last_used_at'] ?? 'Never') ?></td><td style="text-align:right"><button class="btn btn-danger btn-sm" data-api-revoke="<?= e($token['id']) ?>">Revoke</button></td></tr><?php endforeach; ?>
<?php if (!$tokens): ?><tr><td colspan="4" class="text-tertiary" style="text-align:center;padding:24px">No API keys have been generated.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="card"><div class="card-header"><h3>Usage</h3></div><div class="card-pad"><p class="text-tertiary" style="font-size:13px;margin-top:0">Send the key as <span class="mono">Authorization: Bearer TOKEN</span>. API routes are the same as the panel routes under <span class="mono"><?= e(base_url()) ?>/?r=api/…</span>.</p><pre class="mono" style="white-space:pre-wrap;margin:0">curl -H "Authorization: Bearer nbp_…" "<?= e(base_url()) ?>/?r=api/health"</pre></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const{apiPost,toast}=window.Nebula;document.getElementById('apiGenerate')?.addEventListener('click',async()=>{const label=document.getElementById('apiLabel').value.trim();if(!label){toast('Enter a key label','warning');return}const res=await apiPost('tokens',{action:'generate',label});if(res.ok){const box=document.getElementById('apiReveal');document.getElementById('apiPlain').value=res.token;box.style.display='';box.scrollIntoView({behavior:'smooth'});toast('API key generated','success')}else toast(res.error||'Failed','error')});document.getElementById('apiCopy')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(document.getElementById('apiPlain').value);toast('Copied','success')});document.querySelectorAll('[data-api-revoke]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('Revoke this API key?'))return;const res=await apiPost('tokens',{action:'revoke',id:btn.dataset.apiRevoke});if(res.ok){toast('Key revoked','success');setTimeout(()=>location.reload(),300)}else toast(res.error||'Failed','error')}))});</script>
