<?php
require_once APP_ROOT . '/lib/mod_sites.php';
require_once APP_ROOT . '/lib/mod_dns.php';
$sites=sites_list();$domains=array_values(array_filter(array_map(fn($s)=>(string)($s['domain']??''),$sites)));
$selected=(string)($_GET['domain']??($domains[0]??''));if(!in_array($selected,$domains,true))$selected=(string)($domains[0]??'');
$records=$selected!==''?dns_zone_records($selected):[];$nameservers=dns_nameservers();
$badge=['A'=>'badge-blue','AAAA'=>'badge-blue','CNAME'=>'badge-purple','MX'=>'badge-purple','TXT'=>'badge-slate','NS'=>'badge-slate','SRV'=>'badge-slate','CAA'=>'badge-slate'];
?>
<div class="page-header">
  <div><h1 class="page-title">DNS</h1><p class="page-subtitle"><?= count($domains) ?> zone<?= count($domains)===1?'':'s' ?> · authoritative records served by Nebula Panel</p></div>
</div>
<?php if($domains): ?><div class="notice notice-info" style="margin-bottom:16px"><i data-lucide="info"></i><div><strong>Delegate domains to your Nebula nameservers</strong><div>At your registrar, set the nameservers to <?php foreach($nameservers as $i=>$ns): ?><?= $i ? ' and ' : '' ?><span class="mono"><?= e($ns) ?></span><?php endforeach; ?>. Records below are then published by this server.</div></div></div><?php endif; ?>
<?php if(!$domains): ?><?= requirement_missing('network', 'No DNS zones yet', 'Each website’s domain gets a zone here automatically.', [['label' => 'Add website', 'href' => url('websites') . '#add', 'icon' => 'plus', 'primary' => true]]) ?><?php else: ?>
<div class="dns-layout">
  <aside class="card dns-zones"><div class="card-header"><h3>Zones</h3><span class="badge badge-slate"><?= count($domains) ?></span></div><div class="card-pad">
    <?php foreach($domains as $domain): ?><a class="dns-zone<?= $domain===$selected?' active':'' ?>"<?= $domain===$selected?' aria-current=page':'' ?> href="<?= e(url('dns',['domain'=>$domain])) ?>"><span class="flex items-center gap-2"><i data-lucide="globe"></i><span><?= e($domain) ?></span></span><i data-lucide="chevron-right" aria-hidden="true"></i></a><?php endforeach; ?>
  </div></aside>
  <div class="card">
    <div class="card-header"><div><h3><?= e($selected) ?> · DNS records</h3><span class="muted"><?= count($records) ?> custom records · NS and SOA are generated automatically</span></div></div>
    <div class="table-wrap"><table class="data-table dns-record-table"><thead><tr><th>Type</th><th>Name</th><th>Value / target</th><th class="num">TTL</th><th class="num">Priority</th><th class="actions-col"><span class="sr-only">Actions</span></th></tr></thead><tbody>
      <?php foreach($records as $record): ?><tr><td><span class="badge <?= e($badge[$record['type']]??'badge-slate') ?>"><?= e($record['type']) ?></span></td><td class="mono"><?= e($record['name']) ?></td><td class="mono text-tertiary" style="max-width:420px;white-space:normal;word-break:break-all"><?= e($record['value']) ?></td><td class="mono num"><?= (int)$record['ttl'] ?></td><td class="mono num"><?= $record['type']==='MX'?(int)($record['priority']??10):'—' ?></td><td class="actions-col"><button class="icon-btn danger" type="button" data-dns-delete="<?= e($record['id']) ?>" title="Delete record"><i data-lucide="trash-2"></i></button></td></tr><?php endforeach; ?>
      <?php if(!$records): ?><tr class="empty-row"><td colspan="6">No custom records. Add the first record below.</td></tr><?php endif; ?>
    </tbody><tfoot><tr class="dns-add-row"><td><select class="select input-sm" id="dnsType" aria-label="Record type"><?php foreach(['A','AAAA','CNAME','MX','TXT','NS','SRV','CAA'] as $type): ?><option><?= e($type) ?></option><?php endforeach; ?></select></td><td><input class="input input-sm mono" id="dnsName" value="@" placeholder="@ or www" aria-label="Record name"></td><td><input class="input input-sm mono" id="dnsValue" placeholder="Value or target" aria-label="Record value"></td><td><input class="input input-sm mono" id="dnsTtl" value="3600" type="number" min="60" aria-label="TTL in seconds"></td><td><input class="input input-sm mono" id="dnsPriority" value="10" type="number" min="0" aria-label="MX priority"></td><td class="actions-col"><button class="btn btn-primary btn-sm" type="button" id="dnsAdd"><i data-lucide="plus"></i>Add</button></td></tr></tfoot></table></div>
  </div>
</div>
<?php endif; ?>
<script>
document.addEventListener('DOMContentLoaded',()=>{const{apiPost,toast}=window.Nebula;const domain=<?= json_encode($selected) ?>;const type=document.getElementById('dnsType'),priority=document.getElementById('dnsPriority');const sync=()=>{if(!type||!priority)return;priority.disabled=type.value!=='MX';};type?.addEventListener('change',sync);sync();document.getElementById('dnsAdd')?.addEventListener('click',async()=>{const valueInput=document.getElementById('dnsValue');if(!valueInput.value.trim()){window.Nebula.setFieldError(valueInput,'Enter a value.');valueInput.focus();return;}const res=await apiPost('dns',{action:'add',domain,type:type.value,name:document.getElementById('dnsName').value,value:document.getElementById('dnsValue').value,ttl:+document.getElementById('dnsTtl').value,priority:+priority.value});if(res.ok){toast(res.published===false?(res.warning||'Record saved; DNS publishing is not configured'):'DNS record published',res.published===false?'warning':'success');setTimeout(()=>location.reload(),450);}else toast(res.error||'Could not add record','error');});document.querySelectorAll('[data-dns-delete]').forEach(btn=>btn.addEventListener('click',async()=>{if(!await window.Nebula.confirm({title:'Delete this DNS record?',message:'The change is published to the zone immediately.',danger:true}))return;const res=await apiPost('dns',{action:'delete',domain,id:btn.dataset.dnsDelete});if(res.ok){toast('DNS record deleted','success');setTimeout(()=>location.reload(),350);}else toast(res.error||'Could not delete record','error');}));});
</script>
