<?php require_once APP_ROOT.'/lib/mod_docker.php';$available=dk_available(); ?>
<div class="page-header"><div><h1 class="page-title">Docker</h1><p class="page-subtitle" id="dockerSubtitle">Containers, images, volumes and networks</p></div><?php if($available): ?><div class="page-actions"><button class="btn btn-secondary" id="dkPullOpen"><i data-lucide="download"></i>Pull image</button><button class="btn btn-primary" id="dkCreateOpen"><i data-lucide="plus"></i>New container</button></div><?php endif; ?></div>
<?php if(!$available): ?><div class="card"><div class="empty-state"><div class="es-icon"><i data-lucide="box"></i></div><div style="font-weight:600">Docker not installed</div><div style="font-size:13px;margin-top:4px">Install Docker Engine to manage containers here.</div></div></div><?php else: ?>
<div class="grid grid-4" style="margin-bottom:16px"><div class="stat-card"><div class="stat-val" id="dkCountC">–</div><div class="stat-label">Containers</div></div><div class="stat-card"><div class="stat-val" id="dkCountR">–</div><div class="stat-label">Running</div></div><div class="stat-card"><div class="stat-val" id="dkCountI">–</div><div class="stat-label">Images</div></div><div class="stat-card"><div class="stat-val" id="dkCountV">–</div><div class="stat-label">Volumes</div></div></div>
<div class="card docker-manager"><div class="tabs" id="dockerTabs"><button class="tab active" data-tab-target="dkPanelContainers"><i data-lucide="container"></i>Containers <span class="badge badge-slate" id="dkBadgeC">0</span></button><button class="tab" data-tab-target="dkPanelImages"><i data-lucide="layers-3"></i>Images <span class="badge badge-slate" id="dkBadgeI">0</span></button><button class="tab" data-tab-target="dkPanelVolumes"><i data-lucide="database"></i>Volumes <span class="badge badge-slate" id="dkBadgeV">0</span></button><button class="tab" data-tab-target="dkPanelNetworks"><i data-lucide="network"></i>Networks <span class="badge badge-slate" id="dkBadgeN">0</span></button><button class="tab" data-tab-target="dkPanelStacks"><i data-lucide="layers"></i>Stacks <span class="badge badge-slate" id="dkBadgeS">0</span></button><button class="tab" data-tab-target="dkPanelStore"><i data-lucide="store"></i>App Store</button></div>
<div data-tab-panels>
  <section data-tab-panel id="dkPanelContainers"><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Image</th><th>Status</th><th>Container ID</th><th style="text-align:right">Actions</th></tr></thead><tbody id="dkContainers"></tbody></table></div></section>
  <section data-tab-panel id="dkPanelImages" class="hidden"><div class="table-wrap"><table class="data-table"><thead><tr><th>Repository:tag</th><th>Image ID</th><th>Size</th><th style="text-align:right">Actions</th></tr></thead><tbody id="dkImages"></tbody></table></div></section>
  <section data-tab-panel id="dkPanelVolumes" class="hidden"><div class="resource-create"><input class="input" id="dkVolumeName" placeholder="volume_name"><button class="btn btn-primary btn-sm" data-resource-create="volume"><i data-lucide="plus"></i>Create volume</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Driver</th><th>Mountpoint</th><th style="text-align:right">Actions</th></tr></thead><tbody id="dkVolumes"></tbody></table></div></section>
  <section data-tab-panel id="dkPanelNetworks" class="hidden"><div class="resource-create"><input class="input" id="dkNetworkName" placeholder="network_name"><button class="btn btn-primary btn-sm" data-resource-create="network"><i data-lucide="plus"></i>Create network</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Driver</th><th>Scope</th><th>Network ID</th><th style="text-align:right">Actions</th></tr></thead><tbody id="dkNetworks"></tbody></table></div></section>
  <section data-tab-panel id="dkPanelStacks" class="hidden"><div class="resource-create"><button class="btn btn-primary btn-sm" id="dkStackNew"><i data-lucide="plus"></i>New stack</button><button class="btn btn-secondary btn-sm" id="dkStacksRefresh"><i data-lucide="refresh-cw"></i>Refresh</button><span class="muted" style="font-size:12px;align-self:center">Compose projects deployed from an editable docker-compose.yml</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Stack</th><th>Status</th><th>Updated</th><th style="text-align:right">Actions</th></tr></thead><tbody id="dkStacks"></tbody></table></div></section>
  <section data-tab-panel id="dkPanelStore" class="hidden"><div class="resource-create" style="border-bottom:1px solid var(--border-subtle)"><i data-lucide="store" style="width:16px;color:var(--blue-400)"></i><span class="muted" style="font-size:12px;align-self:center">One-click install popular self-hosted apps as compose stacks. Change default passwords after install.</span></div><div class="card-pad"><div class="grid" id="dkStore" style="grid-template-columns:repeat(auto-fill,minmax(255px,1fr));gap:14px"></div></div></section>
</div></div>

<div class="drawer-overlay hidden" id="dkCreateDrawer"><div class="drawer"><div class="drawer-header"><div><strong>New container</strong><div class="muted" style="font-size:11px">Create and start a Docker container</div></div><button class="icon-btn" data-close-docker><i data-lucide="x"></i></button></div><div class="drawer-body"><div class="form-stack"><div><label class="field-label">Name</label><input class="input" id="dkName" placeholder="web-app"></div><div><label class="field-label">Image</label><input class="input mono" id="dkImage" placeholder="nginx:latest"></div><div><label class="field-label">Port mappings</label><input class="input mono" id="dkPorts" placeholder="8080:80, 8443:443"><div class="field-help">Comma-separated host:container mappings.</div></div><div><label class="field-label">Volume mounts</label><textarea class="input mono" id="dkMounts" rows="4" placeholder="app_data:/var/lib/app&#10;/srv/config:/etc/app:ro"></textarea></div><div><label class="field-label">Environment variables</label><textarea class="input mono" id="dkEnv" rows="4" placeholder="APP_ENV=production&#10;TZ=Europe/London"></textarea></div><div><label class="field-label">Restart policy</label><select class="select" id="dkRestart"><option>unless-stopped</option><option>always</option><option>on-failure</option><option>no</option></select></div></div></div><div class="drawer-footer"><button class="btn btn-secondary" data-close-docker>Cancel</button><button class="btn btn-primary" id="dkCreate"><i data-lucide="play"></i>Create &amp; start</button></div></div></div>
<div class="drawer-overlay hidden" id="dkPullDrawer"><div class="drawer"><div class="drawer-header"><strong>Pull image</strong><button class="icon-btn" data-close-docker><i data-lucide="x"></i></button></div><div class="drawer-body"><label class="field-label">Registry image</label><input class="input mono" id="dkPullImage" placeholder="redis:7-alpine"><div class="field-help">Docker Hub images work without a registry prefix.</div></div><div class="drawer-footer"><button class="btn btn-secondary" data-close-docker>Cancel</button><button class="btn btn-primary" id="dkPull"><i data-lucide="download"></i>Pull image</button></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const{apiGet,apiPost,toast}=window.Nebula;let data={};const mk=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};const empty=(body,cols,text)=>{const tr=mk('tr'),td=mk('td','text-tertiary',text);td.colSpan=cols;td.style.cssText='text-align:center;padding:28px';tr.append(td);body.append(tr);};const action=(icon,title,fn,danger=false)=>{const b=mk('button','icon-btn');b.title=title;if(danger)b.style.color='var(--red-400)';b.innerHTML=`<i data-lucide="${icon}"></i>`;b.addEventListener('click',fn);return b;};
async function op(payload,success){const r=await apiPost('docker',payload);toast(r.ok?success:(r.error||'Docker operation failed'),r.ok?'success':'error');if(r.ok)load();return r;}
function render(){const c=data.containers||[],i=data.images||[],v=data.volumes||[],n=data.networks||[];document.getElementById('dockerSubtitle').textContent=`Docker Engine ${data.version||'–'} · ${c.length} containers · ${c.filter(x=>x.state==='running').length} running`;[['dkCountC',c.length],['dkCountR',c.filter(x=>x.state==='running').length],['dkCountI',i.length],['dkCountV',v.length],['dkBadgeC',c.length],['dkBadgeI',i.length],['dkBadgeV',v.length],['dkBadgeN',n.length]].forEach(([id,val])=>document.getElementById(id).textContent=val);
const cb=document.getElementById('dkContainers');cb.innerHTML='';c.forEach(x=>{const tr=mk('tr');tr.append(mk('td','',x.name),mk('td','mono',x.image));const st=mk('td');st.append(mk('span',`badge ${x.state==='running'?'badge-emerald':'badge-slate'}`,x.status||x.state));tr.append(st,mk('td','mono text-tertiary',x.id));const td=mk('td');td.style.textAlign='right';if(x.state!=='running')td.append(action('play','Start',()=>op({action:'container',id:x.id,op:'start'},'Container started')));else td.append(action('square','Stop',()=>op({action:'container',id:x.id,op:'stop'},'Container stopped')));td.append(action('rotate-cw','Restart',()=>op({action:'container',id:x.id,op:'restart'},'Container restarted')),action('trash-2','Remove',()=>confirm(`Remove ${x.name}?`)&&op({action:'container',id:x.id,op:'remove'},'Container removed'),true));tr.append(td);cb.append(tr);});if(!c.length)empty(cb,5,'No containers. Create one to get started.');
const ib=document.getElementById('dkImages');ib.innerHTML='';i.forEach(x=>{const tr=mk('tr');tr.append(mk('td','mono',`${x.repo}:${x.tag}`),mk('td','mono text-tertiary',x.id),mk('td','text-tertiary',x.size));const td=mk('td');td.style.textAlign='right';td.append(action('trash-2','Remove image',()=>confirm('Remove this image?')&&op({action:'image_remove',id:x.id},'Image removed'),true));tr.append(td);ib.append(tr);});if(!i.length)empty(ib,4,'No local images.');
const vb=document.getElementById('dkVolumes');vb.innerHTML='';v.forEach(x=>{const tr=mk('tr');tr.append(mk('td','mono',x.name),mk('td','text-tertiary',x.driver),mk('td','mono text-tertiary',x.mountpoint||'–'));const td=mk('td');td.style.textAlign='right';td.append(action('trash-2','Remove volume',()=>confirm(`Remove volume ${x.name}?`)&&op({action:'volume_remove',name:x.name},'Volume removed'),true));tr.append(td);vb.append(tr);});if(!v.length)empty(vb,4,'No volumes.');
const nb=document.getElementById('dkNetworks');nb.innerHTML='';n.forEach(x=>{const tr=mk('tr');tr.append(mk('td','mono',x.name),mk('td','text-tertiary',x.driver),mk('td','text-tertiary',x.scope),mk('td','mono text-tertiary',x.id));const td=mk('td');td.style.textAlign='right';if(!['bridge','host','none'].includes(x.name))td.append(action('trash-2','Remove network',()=>confirm(`Remove network ${x.name}?`)&&op({action:'network_remove',name:x.name},'Network removed'),true));tr.append(td);nb.append(tr);});if(!n.length)empty(nb,5,'No networks.');if(window.lucide)lucide.createIcons();}
async function load(){try{data=await apiGet('docker');render();}catch(e){toast(e.message||'Could not load Docker','error');}}document.getElementById('dkCreateOpen').onclick=()=>document.getElementById('dkCreateDrawer').classList.remove('hidden');document.getElementById('dkPullOpen').onclick=()=>document.getElementById('dkPullDrawer').classList.remove('hidden');document.querySelectorAll('[data-close-docker]').forEach(b=>b.onclick=()=>b.closest('.drawer-overlay').classList.add('hidden'));document.getElementById('dkCreate').onclick=async()=>{const r=await op({action:'create_container',name:document.getElementById('dkName').value,image:document.getElementById('dkImage').value,ports:document.getElementById('dkPorts').value,volumes:document.getElementById('dkMounts').value,env:document.getElementById('dkEnv').value,restart:document.getElementById('dkRestart').value},'Container created');if(r.ok)document.getElementById('dkCreateDrawer').classList.add('hidden');};document.getElementById('dkPull').onclick=async()=>{const r=await op({action:'image_pull',image:document.getElementById('dkPullImage').value},'Image pulled');if(r.ok)document.getElementById('dkPullDrawer').classList.add('hidden');};document.querySelectorAll('[data-resource-create]').forEach(b=>b.onclick=()=>{const kind=b.dataset.resourceCreate,id=kind==='volume'?'dkVolumeName':'dkNetworkName',name=document.getElementById(id).value.trim();if(name)op({action:`${kind}_create`,name},`${kind} created`);});load();});
</script>

<!-- Compose stacks + app store -->
<div class="drawer-overlay hidden" id="dkStackDrawer"><div class="drawer" style="width:min(780px,96vw)"><div class="drawer-header"><div><strong id="dkStackTitle">New stack</strong><div class="muted" style="font-size:11px">Edit the compose file, then save or deploy</div></div><button class="icon-btn" data-close-overlay><i data-lucide="x"></i></button></div><div class="drawer-body"><div class="form-stack"><div id="dkStackNameRow"><label class="field-label">Stack name</label><input class="input mono" id="dkStackName" placeholder="my-stack" autocomplete="off"><div class="field-help">Lower-case letters, numbers, dashes or underscores.</div></div><div><label class="field-label">docker-compose.yml</label><div class="code-editor-host" style="border:1px solid var(--border-default);border-radius:8px;overflow:hidden"><textarea id="dkStackYaml" class="input mono" style="width:100%;height:46vh;white-space:pre;border:0"></textarea></div></div><pre class="mono hidden" id="dkStackOut" style="margin:0;padding:12px;font-size:12px;line-height:1.5;white-space:pre-wrap;max-height:26vh;overflow:auto;background:var(--bg-surface-2);border-radius:8px"></pre></div></div><div class="drawer-footer"><button class="btn btn-secondary" data-close-overlay>Close</button><button class="btn btn-secondary" id="dkStackSave"><i data-lucide="save"></i>Save</button><button class="btn btn-primary" id="dkStackDeploy"><i data-lucide="play"></i>Save &amp; deploy</button></div></div></div>
<div class="drawer-overlay hidden" id="dkInstallDrawer"><div class="drawer"><div class="drawer-header"><div><strong id="dkInstallTitle">Install app</strong><div class="muted" id="dkInstallDesc" style="font-size:11px"></div></div><button class="icon-btn" data-close-overlay><i data-lucide="x"></i></button></div><div class="drawer-body"><div class="form-stack"><div><label class="field-label">Stack name</label><input class="input mono" id="dkInstallName" autocomplete="off"></div><div class="field-help" id="dkInstallHint"></div><pre class="mono hidden" id="dkInstallOut" style="margin:0;padding:12px;font-size:12px;line-height:1.5;white-space:pre-wrap;max-height:32vh;overflow:auto;background:var(--bg-surface-2);border-radius:8px"></pre></div></div><div class="drawer-footer"><button class="btn btn-secondary" data-close-overlay>Cancel</button><button class="btn btn-primary" id="dkInstallRun"><i data-lucide="download"></i>Install &amp; start</button></div></div></div>
<div class="drawer-overlay hidden" id="dkLogsDrawer"><div class="drawer" style="width:min(860px,96vw)"><div class="drawer-header"><div><strong id="dkLogsTitle">Logs</strong><div class="muted" style="font-size:11px">Last 200 lines</div></div><button class="icon-btn" data-close-overlay><i data-lucide="x"></i></button></div><div class="drawer-body"><pre class="mono" id="dkLogsBody" style="margin:0;font-size:12px;line-height:1.5;white-space:pre-wrap;word-break:break-word"></pre></div></div></div>
<link rel="stylesheet" href="<?= e(asset('vendor/codemirror-5.65.16.min.css')) ?>">
<link rel="stylesheet" href="<?= e(asset('vendor/codemirror-material-darker-5.65.16.min.css')) ?>">
<script src="<?= e(asset('vendor/codemirror-5.65.16.min.js')) ?>"></script>
<script src="<?= e(asset('vendor/codemirror-yaml-5.65.16.min.js')) ?>"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{const{apiGet,apiPost,streamPost,toast}=window.Nebula;let cdata={stacks:[],catalog:[]},editor=null,editMode='new';
const $=id=>document.getElementById(id);
const closeAll=ov=>ov.classList.add('hidden');
document.querySelectorAll('[data-close-overlay]').forEach(b=>b.onclick=()=>closeAll(b.closest('.drawer-overlay')));
const mk=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const iconBtn=(icon,title,fn,danger)=>{const b=mk('button','icon-btn');b.title=title;if(danger)b.style.color='var(--red-400)';b.innerHTML=`<i data-lucide="${icon}"></i>`;b.onclick=fn;return b;};
const fmtTime=ts=>ts?new Date(ts*1000).toLocaleString():'—';

async function loadCompose(){try{cdata=await apiGet('compose');}catch(e){cdata={stacks:[],catalog:[]};}renderStacks();renderStore();}
function renderStacks(){const body=$('dkStacks');if(!body)return;body.innerHTML='';$('dkBadgeS').textContent=cdata.stacks.length;
 cdata.stacks.forEach(s=>{const tr=mk('tr');tr.append(mk('td','',s.name));const st=mk('td');const badge=mk('span',`badge ${s.running?'badge-emerald':'badge-slate'}`,s.status||(s.exists?'stopped':'no compose file'));if(s.running){const d=mk('span','bdot');badge.prepend(d);}st.append(badge);tr.append(st,mk('td','text-tertiary',fmtTime(s.updated)));
  const td=mk('td');td.style.textAlign='right';
  if(s.running)td.append(iconBtn('square','Stop',()=>stackOp(s.name,'stop','Stack stopped')));else td.append(iconBtn('play','Deploy / start',()=>stackStream(s.name,'up','Stack deployed')));
  td.append(iconBtn('rotate-cw','Restart',()=>stackStream(s.name,'restart','Stack restarted')),iconBtn('download','Pull images',()=>stackStream(s.name,'pull','Images pulled')),iconBtn('scroll-text','Logs',()=>viewLogs(s.name)),iconBtn('pencil','Edit compose',()=>openEditor(s.name)),iconBtn('trash-2','Remove stack',()=>removeStack(s.name),true));
  tr.append(td);body.append(tr);});
 if(!cdata.stacks.length){const tr=mk('tr'),td=mk('td','text-tertiary','No stacks yet. Create one or install from the App Store.');td.colSpan=4;td.style.cssText='text-align:center;padding:28px';tr.append(td);body.append(tr);}
 if(window.lucide)lucide.createIcons();}
function renderStore(){const grid=$('dkStore');if(!grid)return;grid.innerHTML='';
 cdata.catalog.forEach(a=>{const card=mk('div','card');card.style.padding='15px';
  const head=mk('div','flex items-center gap-3');head.style.marginBottom='10px';
  const ic=mk('div');ic.style.cssText='width:38px;height:38px;border-radius:10px;background:rgba(59,130,246,.12);display:flex;align-items:center;justify-content:center;flex-shrink:0';ic.innerHTML=`<i data-lucide="${a.icon||'box'}" style="color:var(--blue-400)"></i>`;
  const ti=mk('div');ti.style.minWidth='0';ti.append(mk('div','',a.name));const cat=mk('div','muted',a.category);cat.style.fontSize='11px';ti.append(cat);ti.firstChild.style.cssText='font-weight:700;font-size:14px';
  head.append(ic,ti);
  const desc=mk('div','muted',a.description);desc.style.cssText='font-size:12px;min-height:34px;margin-bottom:10px';
  const foot=mk('div','flex items-center gap-2');const port=mk('span','badge badge-slate',a.port?`:${a.port}`:'no port');foot.append(port);const spacer=mk('div');spacer.style.flex='1';const btn=mk('button','btn btn-primary btn-sm');btn.innerHTML='<i data-lucide="download"></i>Install';btn.onclick=()=>openInstall(a);foot.append(spacer,btn);
  card.append(head,desc,foot);grid.append(card);});
 if(window.lucide)lucide.createIcons();}

async function stackOp(name,action,ok){const r=await apiPost('compose',{action,name});toast(r.ok?ok:(r.error||'Compose action failed'),r.ok?'success':'error');if(r.ok)loadCompose();}
async function stackStream(name,action,ok){const out=$('dkStackOut');const drawerOpen=!$('dkStackDrawer').classList.contains('hidden')&&editMode!=='new'&&$('dkStackName').value===name;let sink=null;if(drawerOpen){out.classList.remove('hidden');out.textContent='';sink=t=>{out.textContent+=t;out.scrollTop=out.scrollHeight;};}toast(`${action}…`,'info');const r=await streamPost('compose',{action,name},ev=>{if(ev.type==='output'&&sink)sink(ev.text);});toast(r.ok?ok:(r.error||'Compose action failed'),r.ok?'success':'error');loadCompose();}
async function removeStack(name){if(!confirm(`Remove stack "${name}"? Containers are stopped and the compose file deleted.`))return;const vols=confirm('Also delete named volumes for this stack? This erases its data. OK = delete volumes, Cancel = keep volumes.');const r=await streamPost('compose',{action:'remove',name,volumes:vols},()=>{});toast(r.ok?'Stack removed':(r.error||'Remove failed'),r.ok?'success':'error');loadCompose();}
async function viewLogs(name){$('dkLogsTitle').textContent=`${name} · logs`;$('dkLogsBody').textContent='Loading…';$('dkLogsDrawer').classList.remove('hidden');const r=await apiPost('compose',{action:'logs',name});$('dkLogsBody').textContent=r.ok?(r.logs||'(no output)'):(r.error||'Could not read logs');}

function ensureEditor(){if(editor)return editor;const ta=$('dkStackYaml');if(window.CodeMirror){editor=CodeMirror.fromTextArea(ta,{mode:'yaml',theme:window.Nebula.cmTheme(),lineNumbers:true,indentUnit:2,tabSize:2,lineWrapping:false,viewportMargin:20});window.Nebula.registerCM(editor);editor.setSize('100%','46vh');}return editor;}
const STARTER="services:\n  app:\n    image: nginx:alpine\n    container_name: my-app\n    restart: unless-stopped\n    ports:\n      - \"8090:80\"\n";
async function openEditor(name){editMode=name?'edit':'new';$('dkStackTitle').textContent=name?`Edit ${name}`:'New stack';$('dkStackOut').classList.add('hidden');$('dkStackOut').textContent='';const row=$('dkStackNameRow'),input=$('dkStackName');ensureEditor();
 const setVal=(val)=>{if(editor)editor.setValue(val);else $('dkStackYaml').value=val;};
 if(name){row.style.display='none';input.value=name;const r=await apiPost('compose',{action:'read',name});setVal(r.ok?r.content:STARTER);}else{row.style.display='';input.value='';setVal(STARTER);}
 $('dkStackDrawer').classList.remove('hidden');setTimeout(()=>editor&&editor.refresh(),30);}
const yamlVal=()=>editor?editor.getValue():$('dkStackYaml').value;
async function saveStack(deploy){const name=(editMode==='edit'?$('dkStackName').value:$('dkStackName').value.trim());if(!name){toast('Enter a stack name','warning');return null;}const r=await apiPost('compose',{action:'save',name,content:yamlVal(),create:editMode==='new'});if(!r.ok){toast(r.error||'Save failed','error');return null;}editMode='edit';$('dkStackNameRow').style.display='none';toast('Compose saved','success');if(!deploy)loadCompose();return name;}
$('dkStackNew')&&($('dkStackNew').onclick=()=>openEditor(null));
$('dkStacksRefresh')&&($('dkStacksRefresh').onclick=loadCompose);
$('dkStackSave').onclick=()=>saveStack(false);
$('dkStackDeploy').onclick=async()=>{const name=await saveStack(true);if(name)stackStream(name,'up','Stack deployed');};

let installApp=null;
function openInstall(a){installApp=a;$('dkInstallTitle').textContent=`Install ${a.name}`;$('dkInstallDesc').textContent=a.description;$('dkInstallName').value=a.key;$('dkInstallHint').textContent=a.port?`Publishes host port ${a.port}. Edit the compose file afterwards to change ports or passwords.`:'Edit the compose file afterwards to configure the app.';$('dkInstallOut').classList.add('hidden');$('dkInstallOut').textContent='';$('dkInstallDrawer').classList.remove('hidden');}
$('dkInstallRun').onclick=async function(){if(!installApp)return;const name=$('dkInstallName').value.trim();const out=$('dkInstallOut');out.classList.remove('hidden');out.textContent='';this.disabled=true;const r=await streamPost('compose',{action:'install',key:installApp.key,name},ev=>{if(ev.type==='output'){out.textContent+=ev.text;out.scrollTop=out.scrollHeight;}});this.disabled=false;toast(r.ok?`${installApp.name} installed`:(r.error||'Install failed'),r.ok?'success':'error');if(r.ok){loadCompose();setTimeout(()=>$('dkInstallDrawer').classList.add('hidden'),900);}};

// Lazy-load compose data the first time either tab is opened, and refresh the editor size.
let composeLoaded=false;document.querySelectorAll('#dockerTabs [data-tab-target]').forEach(t=>t.addEventListener('click',()=>{const tgt=t.dataset.tabTarget;if((tgt==='dkPanelStacks'||tgt==='dkPanelStore')&&!composeLoaded){composeLoaded=true;loadCompose();}}));
});
</script>
<?php endif; ?>
