<?php
require_once APP_ROOT . '/lib/mod_sshkeys.php';
$users = sshkey_users();
$selected = (string) ($_GET['user'] ?? ($users[0]['name'] ?? ''));
if (!sshkey_user_allowed($selected)) { $selected = (string) ($users[0]['name'] ?? ''); }
$keys = $selected ? sshkey_list($selected) : [];
?>
<div class="page-header">
  <div><h1 class="page-title">SSH Keys</h1><p class="page-subtitle">Manage authorized public keys for interactive server users</p></div>
  <?php if ($users): ?><form method="get" class="page-actions"><input type="hidden" name="r" value="sshkeys"><label class="sr-only" for="sshUserSelect">Server user</label><select class="select" name="user" id="sshUserSelect" style="min-width:220px"><?php foreach ($users as $u): ?><option value="<?= e($u['name']) ?>" <?= $u['name'] === $selected ? 'selected' : '' ?>><?= e($u['name']) ?> — <?= e($u['home']) ?></option><?php endforeach; ?></select></form><?php endif; ?>
</div>
<?php if (!helper_available()): ?><?= helper_missing_state('SSH key management') ?>
<?php elseif (!$users): ?><?= requirement_missing('user-x', 'No interactive users', 'SSH keys can be managed for Linux accounts with a login shell. None were found on this server.', [['label' => 'View system accounts', 'href' => url('users') . '#system', 'icon' => 'users']]) ?>
<?php else: ?>
<div class="card" style="margin-bottom:16px"><div class="card-header"><h3>Add public key</h3></div><div class="card-pad"><label class="field-label" for="sshKey">OpenSSH public key<span class="req" aria-hidden="true">*</span></label><textarea class="input mono" id="sshKey" rows="4" required placeholder="ssh-ed25519 AAAA… comment"></textarea><div class="field-help">Paste the contents of a <span class="mono">.pub</span> file. One key at a time.</div><div style="margin-top:12px"><button class="btn btn-primary" type="button" id="sshAdd"><i data-lucide="key-round"></i>Add key</button></div></div></div>
<div class="card"><div class="card-header"><h3>Authorized keys — <?= e($selected) ?></h3><span class="muted"><?= count($keys) ?> key<?= count($keys) === 1 ? '' : 's' ?></span></div><div class="table-wrap"><table class="data-table"><thead><tr><th class="num" style="width:60px">#</th><th>Fingerprint / comment</th><th class="actions-col"><span class="sr-only">Actions</span></th></tr></thead><tbody>
<?php foreach ($keys as $key): ?><tr><td class="mono num"><?= $key['number'] ?></td><td class="mono" style="font-size:12px;word-break:break-all"><?= e($key['meta']) ?></td><td class="actions-col"><button class="btn btn-danger btn-sm" type="button" data-key-delete="<?= $key['number'] ?>"><i data-lucide="trash-2"></i>Remove</button></td></tr><?php endforeach; ?>
<?php if (!$keys): ?><tr class="empty-row"><td colspan="3">No authorized keys for this user.</td></tr><?php endif; ?>
</tbody></table></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const{apiPost,toast}=window.Nebula;const user=<?= json_encode($selected) ?>;document.getElementById('sshUserSelect')?.addEventListener('change',event=>event.currentTarget.form.submit());document.getElementById('sshAdd')?.addEventListener('click',async()=>{const keyInput=document.getElementById('sshKey');const key=keyInput.value.trim();if(!key){window.Nebula.setFieldError(keyInput,'Paste a public key.');keyInput.focus();return;}if(!/^(ssh-(ed25519|rsa|dss)|ecdsa-sha2-nistp(256|384|521)|sk-(ssh-ed25519|ecdsa-sha2-nistp256)@openssh\.com)\s+[A-Za-z0-9+\/=]+/.test(key)){window.Nebula.setFieldError(keyInput,'This does not look like an OpenSSH public key (it should start with ssh-ed25519, ssh-rsa or ecdsa-…).');keyInput.focus();return;}const res=await apiPost('sshkeys',{action:'add',user,key});if(res.ok){toast('SSH key added','success');setTimeout(()=>location.reload(),350)}else toast(res.error||'Failed','error')});document.querySelectorAll('[data-key-delete]').forEach(btn=>btn.addEventListener('click',async()=>{if(!await window.Nebula.confirm({title:'Remove this SSH key?',message:'Anyone using it can no longer sign in as this user.',danger:true,confirmLabel:'Remove key'}))return;const res=await apiPost('sshkeys',{action:'delete',user,number:Number(btn.dataset.keyDelete)});if(res.ok){toast('SSH key removed','success');setTimeout(()=>location.reload(),350)}else toast(res.error||'Failed','error')}))});</script>
<?php endif; ?>
